[package]
name = "vcf_to_csv"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.2.1"
ical = "0.8.0"
vcard_parser = "0.2.1"
